config/routes.rb
EnrolPlanner::Application.routes.draw do

  get "system_manager/db_drop"
  get "system_manager/db_create"
  get "system_manager/db_migrate"
  get "system_manager/db_seed"
  get "system_manager/db_init"
  get "system_manager/update"
  get "system_manager/index"
  resources :pre_req_groups

  resources :planner do
	  collection do
		  get "enrolment_planner"
	  end
  end
  resources :download do
	  collection do
		  get "csv"
		  post "csv"
	  end
  end
  resources :admin
  resources :users
  resources :user_sessions

  resources :units do 
    collection { post :import }
  end

  resources :streams do 
    collection { post :import }
  end

  resources :stream_units do
    collection { post :import }
  end

  resources :pre_req_checker
  
  get "planner/send_email"
  get "planner/sembox"
  get "download/index"
  get "download/pdf"
  get "download/csv"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  
  post "planner/unit_chooser" => "planner#unit_chooser"
  post "planner/enrolment_planner" => "planner#enrolment_planner"
  post "planner/sembox" => "planner#sembox"
  post "planner/send_email" => "planner#send_email"
  post "planner/validate" => "planner#validate"
  post "download/pdf" => "download#pdf"
  post "download/csv" => "download#csv"
  post "admin/login" => "admin#login"
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'users#index'

  
  

end

app/controllers/planner_controller.rb
class PlannerController < ApplicationController
    @stream_units
    helper_method :calc_credits, :calc_sem_credits
    include PlannerHelper

    require "unit_module.rb"

	def show
		@pdfArrPerSem = Array.new
		@pdfArrPerUnit = Array.new
		@sembox = session[:semesters]
		@Enrol_semStart = session[:semesters][0][0]
		@year = 1
		
		@sembox.each_with_index {|sem,index|
		# Enrolment that start from Semester 1

			if (@Enrol_semStart != -1 )# Enrolment started from semester 1 has first array value > -1.
			
				# Semester 2
				if  (@sem_start_at == 2)
					@pdfArrPerUnit.push(["Year" + @year.to_s, "Semester"+ @sem_start_at.to_s])
					sem.each_with_index  do |unit,index|
						#Get Unit Name and Unit ID
						@uName = view_context.get_unit_name(unit.to_i)
						@uCode = view_context.get_unit_code(unit.to_i)
						#Insert into the array
						@pdfArrPerUnit.push([@uCode,@uName])
				
					end
					@pdfArrPerUnit.push([" " , " "])
					#Set Semester to 1 for the next Semester 1
					@sem_start_at -= 1
					#After Semester 2, Year is incremented
					@year += 1
					
				else
					# Semester 1
					@sem_start_at = 1
					@pdfArrPerUnit.push(["Year" + @year.to_s, "Semester"+ @sem_start_at.to_s])
					sem.each_with_index  do |unit,index|
			
						@uName = view_context.get_unit_name(unit.to_i)
						@uCode = view_context.get_unit_code(unit.to_i)
						@pdfArrPerUnit.push([@uCode,@uName])
				
					end
					@pdfArrPerUnit.push([" " , " "])
					#Set Semester to 2 for the next Semester 2
					@sem_start_at += 1
				end
		
			else # Enrolment that start from Semester 2
			#Enrolment started from semester 2 has first array value == -1.
			#Get rid of the -1 in the array
				sem.each_with_index  do |unit,index|
			
						unless (unit < 0)
							@uName = view_context.get_unit_name(unit.to_i)
							@uCode = view_context.get_unit_code(unit.to_i)
							@pdfArrPerUnit.push([@uCode,@uName])
						end
				
				end
			#Next Array value will have @Enrol_semStart > -1
			@Enrol_semStart = 0
			#Set Semester to 2 
			@sem_start_at = 2
		end

		}
		session[:pdf] = @pdfArrPerUnit
		time = Time.now.strftime('%Y%m%d%H%M%S')
		filename = "CoursePlan_" + time
		respond_to do |format|
			format.html
			format.pdf do
			pdf = SemboxPdf.new(@pdfArrPerUnit)
        send_data pdf.render, :disposition => "attachment; filename=#{filename}.pdf", type: 'application/pdf', :page_size => "A4"

			end
		end        
    end
# START stream_chooser
    def index
        @streams = Stream.all

        if @streams.empty?
            @proceed = false
        else
            @proceed = true
        end

        # Clear all session variables to avoid messing with previous data
        clear_enrolment_planner_session
    end

# END stream_chooser


# START unit_chooser
    def unit_chooser
		@units = Unit.all
		@SE = Stream.where(:streamCode => 'STRU-SWENG').first.id
		@IT = Stream.where(:streamCode => 'STRU-INFTC').first.id
		@EU = Unit.where(:unitCode => 'ELEC0000').first.id
		@Elecmath = Unit.where(:unitCode => 'MATH1008').first.id
		@Elecmath2 = Unit.where(:unitCode => 'MATH1007').first.id
		
        if params[:streamSelect].nil? || params[:streamSelect] == 0
            session[:selected_stream] = 0
            @proceed = false
        else
            session[:selected_stream] = params[:streamSelect].to_i
            @proceed = true
        end
		
		all_units_in_stream = StreamUnit.where(:stream_id => session[:selected_stream]).pluck(:unit_id)
		electives_available = Unit.all.pluck(:id) - all_units_in_stream
		@electives_available = Unit.where(:id => electives_available)


        if (@proceed)
            # Get the full list of units of selected stream
            @stream_units = StreamUnit.where(:stream_id => session[:selected_stream].to_i)
			session[:customUnitList]  = Array.new
            if (@stream_units.empty?)
                @proceed = false
            end

			unless (params["maths"].nil?)
            session[:maths] = params["maths"].last
            if ((session[:maths] == "2cd") && ((session[:selected_stream] != 4)&&(session[:selected_stream] != 2)))
				# Put the list into array of StreamUnits, seperated by planned year and semester
				#Change one elective to m136
				#change another one to m135
				twoElecList(@stream_units)
				
            elsif (((session[:maths] == "3ab") && (session[:selected_stream] != 4 && session[:selected_stream] != 2)) || 
				((session[:maths] == "2cd")&&(session[:selected_stream] == 4||session[:selected_stream] == 2)))
                # Replace 2 elective (only one elective for this)
				# Put the list into array of StreamUnits, seperated by planned year and semester
				if (session[:selected_stream] == @IT||session[:selected_stream] == @SE)
					twoElecList(@stream_units)
				else
					oneElecList(@stream_units)		
				end
				
			elsif (((session[:maths] == "3cd")&&(session[:selected_stream] == 4 || session[:selected_stream] == 2)) || 
				((session[:maths] != "3ab")&& (session[:selected_stream] == 4 || session[:selected_stream] == 2)))
				# Replace 1 elective ( 3 elective left for this) (ONLY for IT)
				# Put the list into array of StreamUnits, seperated by planned year and semester
				defaultList(@stream_units)
				
            else
                # Replace 1 elective ( 2 elective left for this) (for others besides IT)
				# Put the list into array of StreamUnits, seperated by planned year and semester

				if (session[:selected_stream] == 4 || session[:selected_stream] == 2)
					oneElecList(@stream_units)
				else
					defaultList(@stream_units)
				end
            end		
        end

		
        end
        debug_print_session
    end
# END unit_chooser

	def defaultList stream_units
		@su_y1s1 = @stream_units.where(:plannedYear => 1).where(:plannedSemester =>1)
			@su_y1s1.each_with_index do |u, i|
				session[:customUnitList].push(u.unit_id)
			end
		@su_y1s2 = @stream_units.where(:plannedYear => 1).where(:plannedSemester =>2)
			@su_y1s2.each_with_index do |u, i|
				session[:customUnitList].push(u.unit_id)
			end
		@su_y2s1 = @stream_units.where(:plannedYear => 2).where(:plannedSemester =>1)
			@su_y2s1.each_with_index do |u, i|
				session[:customUnitList].push(u.unit_id)
			end
		@su_y2s2 = @stream_units.where(:plannedYear => 2).where(:plannedSemester =>2)
			@su_y2s2.each_with_index do |u, i|
				session[:customUnitList].push(u.unit_id)
			end
		@su_y3s1 = @stream_units.where(:plannedYear => 3).where(:plannedSemester =>1)
			@su_y3s1.each_with_index do |u, i|
				session[:customUnitList].push(u.unit_id)
			end
		@su_y3s2 = @stream_units.where(:plannedYear => 3).where(:plannedSemester =>2)
			@su_y3s2.each_with_index do |u, i|
				session[:customUnitList].push(u.unit_id)
			end
		return @su_y1s1, @su_y1s2, @su_y2s1, @su_y2s2, @su_y3s1, @su_y3s2
	end

def oneElecList stream_units
		@totalElec = 0
			@su_y1s1 = @stream_units.where(:plannedYear => 1).where(:plannedSemester =>1)
				@su_y1s1.each_with_index do |u, i|
					session[:customUnitList].push(u.unit_id)
				end
			@su_y1s2 = @stream_units.where(:plannedYear => 1).where(:plannedSemester =>2)
				@su_y1s2.each_with_index do |u, i|
					if (u.unit_id == @EU )
						@totalElec +=1
				        u.unit_id = @Elecmath							
					end
					session[:customUnitList].push(u.unit_id)
				end	
			@su_y2s1 = @stream_units.where(:plannedYear => 2).where(:plannedSemester =>1)
				@su_y2s1.each_with_index do |u, i|
					if (u.unit_id == @EU && @totalElec < 1 )
						@totalElec +=1
						u.unit_id = @Elecmath
					end
					session[:customUnitList].push(u.unit_id)
				end		
			@su_y2s2 = @stream_units.where(:plannedYear => 2).where(:plannedSemester =>2)
				@su_y2s2.each_with_index do |u, i|
					if (u.unit_id == @EU && @totalElec < 1 )
						@totalElec +=1
						u.unit_id = @Elecmath
					end
					session[:customUnitList].push(u.unit_id)
				end	
			@su_y3s1 = @stream_units.where(:plannedYear => 3).where(:plannedSemester =>1)
				@su_y3s1.each_with_index do |u, i|
					if (u.unit_id == @EU && @totalElec < 1 )
						@totalElec +=1
						u.unit_id = @Elecmath
					end
					session[:customUnitList].push(u.unit_id)
				end		
			@su_y3s2 = @stream_units.where(:plannedYear => 3).where(:plannedSemester =>2)
				@su_y3s2.each_with_index do |u, i|
					if (u.unit_id == @EU && @totalElec < 1 )
						@totalElec +=1
						u.unit_id = @Elecmath
					end
					session[:customUnitList].push(u.unit_id)
				end
		return @su_y1s1, @su_y1s2, @su_y2s1, @su_y2s2, @su_y3s1, @su_y3s2
end

def twoElecList stream_units 
		@totalElec = 0
				@su_y1s1 = @stream_units.where(:plannedYear => 1).where(:plannedSemester =>1)
					@su_y1s1.each_with_index do |u, i|
						session[:customUnitList].push(u.unit_id)
					end
				@su_y1s2 =  @stream_units.where(:plannedYear => 1).where(:plannedSemester =>2)
					@su_y1s2.each_with_index do |u, i|
						if (u.unit_id == @EU )
							@totalElec +=1
							u.unit_id = @Elecmath
						end	
						session[:customUnitList].push(u.unit_id)
					end	
				@su_y2s1 = @stream_units.where(:plannedYear => 2).where(:plannedSemester =>1)
					@su_y2s1.each_with_index do |u, i|
						if (u.unit_id == @EU && @totalElec == 1 )
							@totalElec +=1
							u.unit_id = @Elecmath2
						elsif (u.unit_id == @EU && @totalElec < 1 )
							@totalElec +=1
							u.unit_id = @Elecmath
						end
						session[:customUnitList].push(u.unit_id)
					end
					
				@su_y2s2 = @stream_units.where(:plannedYear => 2).where(:plannedSemester =>2)
					@su_y2s2.each_with_index do |u, i|
						if (u.unit_id == @EU && @totalElec == 1 )
							@totalElec +=1
							u.unit_id = @Elecmath2
						elsif (u.unit_id == @EU && @totalElec < 1 )
							@totalElec +=1
							u.unit_id = @Elecmath
						end	
						session[:customUnitList].push(u.unit_id)
					end
				@su_y3s1 = @stream_units.where(:plannedYear => 3).where(:plannedSemester =>1)
					@su_y3s1.each_with_index do |u, i|
						session[:customUnitList].push(u.unit_id)
					end

app/helpers/planner_helper.rb
module PlannerHelper
	
	def export_enrol_planner_csv
		#use a temporary array to generate csv
		rows = []
		#store the streamID, so the remaining units can be calculated upon import
		rows.push({:type => "S", :streamID => session[:selected_stream]})
		#store the planned units for each semester
		session[:semesters].each_with_index do |semUnits, semID|
			semUnits.each do |unitID|
				rows.push({:type => "P", :unitID => unitID, :semID => semID}) # <----- Modified in TASK EPW-314 <-----
			end
		end
		#store the units already completed
		session[:done_units].each do |unitID|
			rows.push({:type => "D", :unitID => unitID})
		end
		# ========== START TASK EPW-314 ============
		#store the remaining units list
		session[:remain_units].each do |unitID|
			rows.push({:type => "R", :unitID => unitID})
		end
		# ========== END TASK EPW-314 ============
		#generate the csv
		csv = CSV.generate do |csv|
			rows.each do |row|
				csv << row.values
			end
		end
		return csv
	end
	
	def import_enrol_planner_csv csvdata
		#clear the enrolment planner session
		clear_enrolment_planner_session
		
		session[:done_units] = []
        session[:plan_units] = []
		session[:semesters] = []
		session[:remain_units] = [] # <----- Added in TASK EPW-314 <-----
		
		#parse csv into session
		CSV.foreach(csvdata.path) do |row|
			type = row[0]
			id = row[1].to_i
			if row[2]
				semID = row[2].to_i
			end
			if (type == "S")
				session[:selected_stream] = id
			elsif (type == "P")
				if (id != 0) # <----- Modified in TASK EPW-314 <-----
					session[:plan_units].push(id)
				end
				if (!session[:semesters][semID])
					session[:semesters][semID] = []
				end
				session[:semesters][semID].push(id)
			elsif (type == "D")
				session[:done_units].push(id)
			# ========== START TASK EPW-314 ============
			elsif (type == "R")
				session[:remain_units].push(id)
			# ========== END TASK EPW-314 ============
			end
		end
		
		# ========== START TASK EPW-314 ============
		
		# handle empty semester (first sem start)
		if session[:semesters].empty?
			session[:semesters]=[[]]
		elsif ((session[:semesters].count == 1) && (session[:semesters][0][0] == -1))
			# handle empty semester (second sem start)
			session[:semesters][1] = []
		end
		
		#populate remaining units for given stream
		#populate_remaining_units(session[:plan_units].concat(session[:done_units]))
		
		# ========== END TASK EPW-314 ============
		
		redirect_to enrolment_planner_planner_index_path, notice: "Session Restored Successfully"
		
	end
	
	def clear_enrolment_planner_session
		session.delete(:selected_stream)
        session.delete(:semesters)
        session.delete(:done_units)
        session.delete(:plan_units)
        session.delete(:remain_units)
        session.delete(:enrol_planner_flag)

        session.delete(:sem0_units)
        session.delete(:sem1_units)
        session.delete(:sem2_units)
        session.delete(:maths)
	end
	
	#assumes selected stream already stored in session
	def populate_remaining_units done_units_array
		@done_units = []
		session[:remain_units] = []
		# Get list of done units with ID integer
		unless done_units_array.nil?
			done_units_array.each do |puid|
				@done_units += StreamUnit.where(:stream_id => session[:selected_stream]).where(:unit_id => puid)
			end
		else
			@done_units = nil
		end
		
		# Get list of remaining units with done units object
		@remain_units = get_remaining_units(@done_units)
		
		# Assign remaining units' IDs to session variable
		@remain_units.each do |ru|
			session[:remain_units].push(ru.unit_id)
		end
		session[:remain_units].sort!
	end
	
	def get_remaining_units done
        # Get StreamUnit where SUs are in "selected stream", and ID is not in "done".
        # Note that where() method returns ActiveRecord object, even if the result is
        # only one entry, it return an ActiveRecord array.
        unless done.nil?
            remain_streamunits = StreamUnit.where(:stream_id => session[:selected_stream]).where('id not in (?)', done)
		else
            remain_streamunits = StreamUnit.where(:stream_id => session[:selected_stream])
        end
        return remain_streamunits
    end
	
end

app/views/planner/_navbar.html.erb
<div class = "navbar navbar-inverse navbar-static-top">			<!--nav bar begins-->

	<div class = "container">

		<div class = ".navbar-header">

			<%= link_to "Enrolment Planner", planner_index_path, class: "navbar-brand" %>

			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
		</div>

		<div class = "collapse navbar-collapse navHeaderCollapse">

			<ul class = "nav navbar-nav navbar-right">

				<li class = "active"><a href="#">Planner</a></li>
				<li><a href="#">Admin</a></li>

			</ul>

		</div>

	</div>

</div>			<!--nav bar ends-->

app/views/planner/getCourseUnits.html.erb
<p>Awaiting implementation of displaying list of units of chosen course in planner index page function...</p>

app/views/planner/index.html.erb
<style type="text/css">
    label {font-weight: normal !important};
</style>
        <div class="col-md-8">
        <div class = "panel panel-info">

            <div class="panel-heading">
                <div class="panel-title text-center">Hello, Welcome to Enrolment Planner</div>
            </div>

            <br>
            <%= form_tag :action => "unit_chooser" do %>
            <div class="panel-body">
                <p class="subheading">Please select your stream:</p>

                <!-- Select stream -->
                <% if (@streams.empty?) %>
                    <select name="streamSelect" class="form-control" style="margin:15px; width:90%;">
                        <option value="0">No stream available.</option>
                    </select>
                <% else %>
                    <%= select_tag "streamSelect", options_from_collection_for_select(@streams, "id", "streamName"), multiple: false, class: 'form-control',  style: "margin-left:15px; width:90%;" %>
                <% end %>

                <br />

                <!-- Select math units -->
                <hr style="border-color:#CCC">
                    <p class="subheading">Please select the maths subjects that you have done:</p>

                    <div style="margin-left:15px; margin-top:10px;">
						<input type="checkbox" checked="true" style="display:none;" name="maths[]" value="2cd">
                        <label><input type="checkbox" checked="true" disabled="true"> Mathematics 2C/D</label><br />
                        <label><input type="checkbox" name="maths[]" value="3ab"> Mathematics 3A/B</label><br />
                        <label><input type="checkbox" name="maths[]" value="3cd"> Mathematics 3C/D</label><br />

                    </div>

                <!-- Proceed button -->
                <% if @proceed %>
                    <%= submit_tag "Proceed", class: "btn btn-info pull-right", style: "width:150px" %>
                <% else %>
                    <%= submit_tag "Proceed", class: "btn btn-info pull-right disabled", style: "width:150px" %>
                <% end %>

            <% end %>
            </div>

        </div>
        </div>
        
        <div class="col-md-3 col-md-offset-1"> <!-- upload your CSV -->
            <div class="panel panel-info">

                <div class="panel-heading">
                    <h3 class="panel-title"><center>Continue Previous Session</center></h3>
                </div>      

                <div class="panel-body" style="overflow:hidden;">
                    <%= form_tag download_csv_path, multipart: true do %>
                    <div class="form-group">
                        <%= file_field_tag :file, accept: 'text/csv' %><br>
                        <%= submit_tag "Upload CSV File", class: 'btn btn-info btn-sm pull-right' %>
                    </div>
                    <% end %>
                </div>

            </div>
        </div>      <!-- end of upload your CSV -->

app/views/planner/send_email.html.erb
<script type="text/javascript">
    window.location.href = "/planner/enrolment_planner";
</script>

app/views/planner/show.html.erb
<script type="text/javascript">
    window.location.href = "/planner";
</script>