config/routes.rb
EnrolPlanner::Application.routes.draw do

  get "system_manager/db_drop"
  get "system_manager/db_create"
  get "system_manager/db_migrate"
  get "system_manager/db_seed"
  get "system_manager/db_init"
  get "system_manager/update"
  get "system_manager/index"
  resources :pre_req_groups

  resources :planner do
	  collection do
		  get "enrolment_planner"
	  end
  end
  resources :download do
	  collection do
		  get "csv"
		  post "csv"
	  end
  end
  resources :admin
  resources :users
  resources :user_sessions

  resources :units do 
    collection { post :import }
  end

  resources :streams do 
    collection { post :import }
  end

  resources :stream_units do
    collection { post :import }
  end

  resources :pre_req_checker
  
  get "planner/send_email"
  get "planner/sembox"
  get "download/index"
  get "download/pdf"
  get "download/csv"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  
  post "planner/unit_chooser" => "planner#unit_chooser"
  post "planner/enrolment_planner" => "planner#enrolment_planner"
  post "planner/sembox" => "planner#sembox"
  post "planner/send_email" => "planner#send_email"
  post "planner/validate" => "planner#validate"
  post "download/pdf" => "download#pdf"
  post "download/csv" => "download#csv"
  post "admin/login" => "admin#login"
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'users#index'

  
  

end

app/views/admin/index.html.erb
<!-- Navigation bar -->
<ol class="breadcrumb">
  <li class="active"><b>Admin Portal</b></li>
</ol>

<!-- START course management -->
	<!-- START update units -->
	<div class = "panel panel-success">
		<div class = "panel-heading"><div class="panel-title">Update Units</div></div>
		<div class = "panel-body">
			<div class = "col-md-6">
				<%= form_tag import_units_path, multipart: true do %>
					<%= file_field_tag :file, accept: 'text/csv' %>
					<br><%= submit_tag "Update Units", class: 'btn btn-success btn-sm' %>
					<%= link_to "Download CSV", units_path(format: "csv"), class: 'btn btn-success btn-sm', style: "color:white;" %>
				<% end %>
			</div>
			<div class = "col-md-6">
				<p class="text-danger"><small><span class="glyphicon glyphicon-exclamation-sign"></span> Its always recomended to create a backup before you try any CSV update attempts, as this action can not be undone.</small></p>
			</div>
		</div>
	</div>
	<!-- END update units -->

	<!-- START update streams -->
	<div class = "panel panel-success">
		<div class = "panel-heading"><div class="panel-title">Update Streams</div></div>
		<div class = "panel-body">
			<div class = "col-md-6">
				<%= form_tag import_streams_path, multipart: true do %>
					<%= file_field_tag :file, accept: 'text/csv'%>
					<br><%= submit_tag "Update Streams", class: 'btn btn-success btn-sm' %>
					<%= link_to "Download CSV", streams_path(format: "csv"), class: 'btn btn-success btn-sm', style: "color:white;" %>
				<% end %>
			</div>
			<div class = "col-md-6">
				<p class="text-danger"><small><span class="glyphicon glyphicon-exclamation-sign"></span> Its always recomended to create a backup before you try any CSV update attempts, as this action can not be undone.</small></p>
			</div>
		</div>
	</div>
	<!-- END update streams -->
<!-- END course management -->

app/views/admin/login.html.erb
<div class="container">    
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
        <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Sign In</div>
                </div>     

                <div style="padding-top:30px" class="panel-body" >

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                        
                    <form id="loginform" class="form-horizontal" role="form">
                                
                        <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="Staff ID" required autofocus />                                        
                                </div>
                            
                        <div style="margin-bottom: 15px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                    <input id="login-password" type="password" class="form-control" name="password" placeholder="Password" required />
                                </div>
                                

                            
                        <div style="margin-bottom: 15px" class="input-group">
                                  <div class="checkbox">
                                    <label>
                                      <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                    </label>
                                  </div>
                                </div>


                            <div style="margin-top:10px" class="form-group">
                                <!-- Button -->

                                <div class="col-sm-12 controls">
                                	<center>
                                 		<button id="btn-login" href="#" class="btn btn-success" style="width: 160px"> Login  </button>
                                  	</center>
                                </div>
                            </div>


                            
                        </form>     



                    </div>                     
                </div>  
    </div> 
</div>