config/routes.rb
EnrolPlanner::Application.routes.draw do

  get "system_manager/db_drop"
  get "system_manager/db_create"
  get "system_manager/db_migrate"
  get "system_manager/db_seed"
  get "system_manager/db_init"
  get "system_manager/update"
  get "system_manager/index"
  resources :pre_req_groups

  resources :planner do
	  collection do
		  get "enrolment_planner"
	  end
  end
  resources :download do
	  collection do
		  get "csv"
		  post "csv"
	  end
  end
  resources :admin
  resources :users
  resources :user_sessions

  resources :units do 
    collection { post :import }
  end

  resources :streams do 
    collection { post :import }
  end

  resources :stream_units do
    collection { post :import }
  end

  resources :pre_req_checker
  
  get "planner/send_email"
  get "planner/sembox"
  get "download/index"
  get "download/pdf"
  get "download/csv"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  
  post "planner/unit_chooser" => "planner#unit_chooser"
  post "planner/enrolment_planner" => "planner#enrolment_planner"
  post "planner/sembox" => "planner#sembox"
  post "planner/send_email" => "planner#send_email"
  post "planner/validate" => "planner#validate"
  post "download/pdf" => "download#pdf"
  post "download/csv" => "download#csv"
  post "admin/login" => "admin#login"
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'users#index'

  
  

end

app/models/unit.rb
class Unit < ActiveRecord::Base 
    validates :unitCode, presence: { strict: true, message: " cannot be empty!" },
                         uniqueness: { strict: true, message: " is duplicated!" },
                         format: { :with => /\A[a-zA-Z]{4}\d{4}\z/i, message: " is in incorrect format!" }
    validates :unitName, presence: { strict: true, message: " cannot be empty!" },
                         length: { :within => 5..100, :too_long => " is too long!", :too_short => " is too short!" }
    validates :creditPoints, presence: { strict: true, message: " cannot be empty!" },
                             numericality: { :greater_than_or_equal_to => 12.5, :less_than_or_equal_to => 50 }
    validates :semAvailable, presence: { strict: true, message: " cannot be empty!" },
                             numericality: { only_integer: true, message: " can only be interger!" },
                             inclusion: { :in => [0,1,2], message: " can only be either 0, 1 or 2!" }
    

    def self.import(file)
        @proceed = false
    
        #Validates the file type
        spreadsheet = open_spreadsheet(file)
    
        #Header of the spreadsheet is the name of the attributes
        header = spreadsheet.row(1)
        if header.eql? ["unitCode","unitName","preUnit","creditPoints","semAvailable"]
            @proceed = true
        else
            return 2
        end
        
        if @proceed
            # Resetting the model to avoid duplication 
            ActiveRecord::Base.connection.execute("TRUNCATE units") 
            ActiveRecord::Base.connection.execute("TRUNCATE pre_req_groups") 
            ActiveRecord::Base.connection.execute("TRUNCATE pre_reqs")

            # Foreach => unit (grap each row from spreadsheet)
            (2..spreadsheet.last_row).each do |i|
                row = Hash[[header, spreadsheet.row(i)].transpose]
                unit = Unit.new
                unit.attributes = row.to_hash.slice(*["id", "unitCode", "unitName", "preUnit", "creditPoints", "semAvailable"])

                # Validates the data of the spreadsheet, save the data into the database if it is valid data.
                if unit.valid?
                    pr_string = unit.preUnit

                    # Assign T/F to preUnit column
                    if unit.preUnit.blank?
                        unit.preUnit = "false"
                    else
                        unit.preUnit = "true"
                    end
                    unit.save!
                    
                    # Check if the unit has pre-requisite
                    unless pr_string.blank?
                        unless pr_string =~ /((\A|;)\{(\D{4}\d{4}){1}(,\D{4}\d{4})*})*\z/
                            return 3
                        end
                        # Splitting preUnit string into groups
                        groups = Array.new(pr_string.count("}"))
                        groups.length.times do |i|
                            groups[i] = pr_string[(pr_string.index("{")+1)..(pr_string.index("}")-1)]
                            pr_string.slice!(0, pr_string.index("}")+1)
                        end

                        # Foreach => pre-requisite group
                        groups.each do |grp|
                            pr_codes = grp.split(',')
                            pr_group = PreReqGroup.new(:unit_id => unit.id)
                            pr_group.save!

                            # Foreach => pre-requisite code
                            pr_codes.each do |prcode|
                                pre_req = PreReq.new(:pre_req_group_id => pr_group.id, :unit_id => unit.id, :preUnit_code => prcode)
                                pre_req.save!
                            end
                        end
                    end
                end # End IF (unit.valid?)
            end # End FOREACH unit
        end
        return 1    # if imported successfully, return true
    end


    def self.to_csv
        CSV.generate do |csv|
            csv << ["unitCode", "unitName", "preUnit", "creditPoints", "semAvailable"]

            # Foreach unit
            all.each do |unit|
                prereq_groups = PreReqGroup.where(:unit_id => unit.id)
                prereq_groups_string = Array.new

                # Foreach pre-req group
                prereq_groups.each do |prg|
                    prereqs = PreReq.where(:pre_req_group_id => prg.id)
                    prereqs_string = Array.new

                    # Foreach pre-req in group
                    prereqs.each do |pr|
                        prereqs_string.push(pr.preUnit_code)
                    end

                    prereq_groups_string.push("{"+prereqs_string.join(',')+"}")
                end

                row = unit.attributes.values_at(*["unitCode", "unitName", "creditPoints", "semAvailable"])
                row.insert(2, prereq_groups_string.join(';'))
                csv << row
            end
        end
    end

    
    def self.open_spreadsheet(file)
        #check the file extension to verity if it is a valid import file type.
        case File.extname(file.original_filename)
            when ".csv" then Roo::Csv.new(file.path)
            when ".xls" then Roo::Excel.new(file.path)
            when ".xlsx" then Roo::Excelx.new(file.path)
        else 
            raise "You have imported an unknown file type: #{file.original_filename}."
        end
    end 
    

    def unit_to_s
        "#{unitCode} #{unitName}"
    end

    def get_prereq_string
        prereq_groups = PreReqGroup.where(:unit_id => self.id)
        prereq_groups_string = Array.new

        # Foreach pre-req group
        prereq_groups.each do |prg|
            prereqs = PreReq.where(:pre_req_group_id => prg.id)
            prereqs_string = Array.new

            # Foreach pre-req in group
            prereqs.each do |pr|
                prereqs_string.push(pr.preUnit_code)
            end

            prereq_groups_string.push("{"+prereqs_string.join(',')+"}")
        end
        return prereq_groups_string.join(',')
    end

    has_many :stream_units, :foreign_key=> :unit_id
    has_many :streams, through: :stream_units

    has_many :pre_reqs, :foreign_key=> :unit_id
    has_many :preUnits, through: :pre_reqs

    has_many :pre_req_groups, :foreign_key=> :unit_id
    validates_uniqueness_of :unitCode
end

app/controllers/units_controller.rb
 class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_filter :require_login

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
    time = Time.now.strftime('%Y%m%d%H%M%S')
    filename = "Units_" + time
    respond_to do |format|
      format.html
      format.csv { send_data @units.to_csv, :disposition => "attachment;filename=#{filename}.csv" }
      format.pdf do
        pdf = UnitPdf.new(@units)
        send_data pdf.render, :disposition => "attachment;filename=#{filename}.pdf", type: 'application/pdf', :page_size => "A4"
      end
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

################ START OF TASK EPW-214 & EPW-215 ################
  # START importing units from CSV
  def import
  	# check if the user attach empty file 
      unless params[:file].nil?
  		# if it is imported successfully, the import method will return 1
  		@message = Unit.import(params[:file])
    		case @message
          when 1
            redirect_to units_path, notice: 'Units Updated Successfully.'
          when 2
            flash[:type] = "danger"
            redirect_to units_path, notice: 'Units import Failed. Incorrect number of columns!'
          when 3
            flash[:type] = "danger"
            redirect_to units_path, notice: 'Units import Failed. Incorrect pre-requisite string format!'
    		end
    	else
        flash[:type] = "warning"
        flash[:notice] = "No file attached!"
    		redirect_to units_path
    	end
  end
  # END importing units from CSV
################ END OF TASK EPW-214 & EPW-215 ################
  
  def not_authenticated
    flash[:type] = "warning"
    redirect_to login_path, notice: "Please login first"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:unitCode, :unitName, :preUnit, :creditPoints, :semAvailable)
    end
end

app/helpers/units_helper.rb
# Helper class for Unit table
# 
# Here you can write helper methods related to Unit table. Be sure 
# when you are importing IDs, parse it to integer in case the import 
# parameter is not in integer which causes exceptions.

module UnitsHelper

    # GETTERS
    def get_unit_code uid
        return Unit.where(:id => uid.to_i).first.unitCode
    end

    def get_unit_name uid
        return Unit.where(:id => uid.to_i).first.unitName
    end

    def get_unit_semavailable uid
        u_semavail = Unit.where(:id => uid.to_i).first.semAvailable
        if (u_semavail == 0)
            return "Both"
        else
            u_semavail
        end
    end

    def get_unit_creditpoints uid
        return Unit.where(:id => uid.to_i).first.creditPoints
    end

    def get_unit_prereq_list uid
        prereq_groups = PreReqGroup.where(:unit_id => uid.to_i)

        prereq_list ||= []

        pre_req_group.each do |prg|
            prereq = PreReq.where(:prereq_groups_id => prg.id.to_i)
            
            prereq.each do |pr|
                prereq_code_list.push(pr.preUnit_code)
            end
        end
        return prereq_code_list.uniq
    end

    def get_uid_by_unitCode ucode
        return Unit.where(:unitCode => ucode).first.id
    end

    def has_done_prereq done_units, semesters, sem_index, uid
        has_done = false

################ START OF TASK EPW-210 ################
# Added T/F checking in database to avoid excessive code
# even the unit has no pre-requisite.

        if (Unit.where(:id => uid.to_i).first.preUnit == "true")
            prereq_groups_id = PreReqGroup.where(:unit_id => uid.to_i)

            puts "Checking pre-req for uid=" + uid.to_s + ":"
            prereq_groups_id.each do |prgroup_id|
                if has_done_prereq_by_group(done_units, semesters, sem_index, prgroup_id.id)
                    return true
                else
                    has_done = false
                end
            end
        else
            return true
        end

################ END OF TASK EPW-210 ################

        return has_done
    end

    def has_done_prereq_by_group done_units, semesters, sem_index, gid
        prereqs = PreReq.where(:pre_req_group_id => gid.to_i)
        prereqs.each do |pr|
            unless has_done_by_code(done_units, semesters, sem_index, pr.preUnit_code)
                return false
            end
        end
        return true
    end

    def has_done_by_code done_units, semesters, sem_index, ucode
        # Grab the UID with UnitCode
        uid = Unit.where(:unitCode => ucode).first.id.to_i
        has_done = false

        # Printing console message.
        puts "done_units = [" + done_units.join(',') + "]"
        print "semester = "
        semesters.each do |sem|
            print "[" + sem.join(',') + "],"
        end
        puts ""
        print "\tuid = " + uid.to_s + " , uCode = " + ucode.to_s + ": "

        # Check if unit is in done_units
        if (done_units.include? uid)
            puts "Done."
            return true
        else
            has_done = false
        end

        # Check if unit is in any of the semesters, except current semester.
        (sem_index).times do |i|
            if (semesters[i].include? uid.to_i)
                puts "Done."
                return true
            else
                has_done = false
            end
        end

        puts "Not done."
        return has_done
    end
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <center>
  <div class="panel panel-success" style="width:50%">
    <div class="panel-heading">
      <%= "Editing unit: " + @unit.unitCode + " - " + @unit.unitName %>
    </div>
    <div class="panel-body" style="text-size: 15px">
          <div class="input-group"><div class="input-group-addon">Unit Code</div><%= f.text_field :unitCode, class: "form-control input-small", style: "width:100%" %></div><br />

          <div class="input-group"><div class="input-group-addon">Unit Name</div><%= f.text_field :unitName, class: "form-control input-small", style: "width:100%" %></div><br />

          <div class="input-group"><div class="input-group-addon">Credit Points</div><%= f.number_field :creditPoints, class: "form-control input-small", style: "width:100%" %></div><br />

          <div class="input-group"><div class="input-group-addon">Semester Available</div><%= f.number_field :semAvailable, class: "form-control input-small", style: "width:100%" %></div><br />
      <%= f.submit class: "btn btn-sm btn-success pull-right" %>
    </div>
  </div>
  </center>
<% end %>

app/views/units/edit.html.erb
<!-- Navigation bar -->
<ol class="breadcrumb">
<li><%= link_to 'Admin Portal', admin_index_path %></li>
<li><%= link_to 'Units List', units_path %></li>
<li><%= link_to @unit.unitName, @unit %></li>
<li class="active"><b>Edit</b></li>
</ol>
<%= render 'form' %>

app/views/units/index.html.erb
<style type="text/css">
  a:hover { background-color: transparent; }
</style>

<!-- Navigation bar -->
<ol class="breadcrumb">
  <li><%= link_to 'Admin Portal', admin_index_path %></li>
  <li class="active"><b><%= 'Units List' %></b></li>
</ol>

<div class="panel panel-success">
  <div class="panel panel-heading"><div class="panel-title" style="text-align:center;">Units</div></div>
  <div class="panel-body">
    <div class="panel panel-default">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Unit Code</th>
            <th>Unit Name</th>
            <th>Pre-requisite</th>
            <th>Credit Points</th>
            <th>Semster Available</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @units.each do |unit| %>
            <tr>
              <td class="unitRow" onclick="document.location='units/<%=unit.id%>'" style="text-align:right;">
                <%= unit.unitCode %>
              </td>
              <td class="unitRow" onclick="document.location='units/<%=unit.id%>'">
                <%= unit.unitName %>
              </td>
              <td class="unitRow" onclick="document.location='units/<%=unit.id%>'">
                <%= unit.preUnit == "true" ? unit.get_prereq_string : "-" %>
              </td>
              <td class="unitRow" class="center" onclick="document.location = 'units/<%=unit.id%>'">
                <%= unit.creditPoints %>
              </td>
              <td class="unitRow" class="center" name="semAvail" onclick="document.location='units/<%=unit.id%>'">
                <%= unit.semAvailable == 0 ? "Both" : unit.semAvailable %>
              </td>
              <td style="text-align:right;">
                <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>"), edit_unit_path(unit), title: 'Edit', style: "color:#666;" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<center>
  <div class="row" style="width:80%;">
    <div class="col-md-6">
      <div class="panel panel-success">
        <div class="panel-heading"><div class="panel-title">Resubmit your CSV</div></div>
        <div class="panel-body" style="text-align:left;">
          <%= form_tag import_units_path, multipart: true do %>
            <%= file_field_tag :file, accept: 'text/csv' %>
            <br>
            <%= submit_tag "Upload Streams", class: 'btn btn-success btn-sm' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-success">
        <div class="panel-heading"><div class="panel-title">Download & Print</div></div>
        <div class="panel-body">
          <%= link_to "Download CSV", units_path(format: "csv"), class: 'btn btn-success btn-sm', style: "color:white;" %>
          <%=link_to_function "Print this Page", "javascript:print()", class: 'btn btn-success btn-sm' %>
        </div>
      </div>
    </div>
  </div>
</center>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<!-- Navigation bar -->
<ol class="breadcrumb">
  <li><%= link_to 'Admin Portal', admin_index_path %></li>
  <li><%= link_to 'Units List', units_path %></li>
  <li class="active"><b><%= @unit.unitName %></b></li>
</ol>

<center>
<div class="panel panel-success" style="width:50%">
  <div class="panel-heading">
    <%= @unit.unitCode + " - " + @unit.unitName %>
    <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>"), edit_unit_path(@unit), class: 'btn btn-default btn-xs pull-right' %>
  </div>
  <div class="panel-body">
    <table class="table">
      <tr>
        <td style="border-top: none; font-weight: bold; width: 30%;">Unit Code:</td>
        <td style="border-top: none;"><%= @unit.unitCode %></td>
      </tr>
      <tr>
        <td style="font-weight: bold;">Unit Name:</td>
        <td><%= @unit.unitName %></td>
      </tr>
      <tr>
        <td style="font-weight: bold;">Pre-requisite(s):</td>
        <td><%= @unit.preUnit == "true" ? @unit.get_prereq_string : "-" %></td>
      </tr>
      <tr>
        <td style="font-weight: bold;">Credit points:</td>
        <td><%= @unit.creditPoints %></td>
      </tr>
      <tr>
        <td style="font-weight: bold;">Semester Available:</td>
        <td><%= @unit.semAvailable == 0? "Both" : @unit.semAvailable %></td>
      </tr>
    </table>
  </div>
</div>
</center>