config/routes.rb
EnrolPlanner::Application.routes.draw do

  get "system_manager/db_drop"
  get "system_manager/db_create"
  get "system_manager/db_migrate"
  get "system_manager/db_seed"
  get "system_manager/db_init"
  get "system_manager/update"
  get "system_manager/index"
  resources :pre_req_groups

  resources :planner do
	  collection do
		  get "enrolment_planner"
	  end
  end
  resources :download do
	  collection do
		  get "csv"
		  post "csv"
	  end
  end
  resources :admin
  resources :users
  resources :user_sessions

  resources :units do 
    collection { post :import }
  end

  resources :streams do 
    collection { post :import }
  end

  resources :stream_units do
    collection { post :import }
  end

  resources :pre_req_checker
  
  get "planner/send_email"
  get "planner/sembox"
  get "download/index"
  get "download/pdf"
  get "download/csv"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  
  post "planner/unit_chooser" => "planner#unit_chooser"
  post "planner/enrolment_planner" => "planner#enrolment_planner"
  post "planner/sembox" => "planner#sembox"
  post "planner/send_email" => "planner#send_email"
  post "planner/validate" => "planner#validate"
  post "download/pdf" => "download#pdf"
  post "download/csv" => "download#csv"
  post "admin/login" => "admin#login"
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'users#index'

  
  

end

app/views/master_layouts/_footer.html.erb
<div class = "navbar navbar-default navbar-fixed-bottom">
	<div class = "container">
		<p class = "navbar-text pull-left">Enrolment Planner © SEP EPW-Web group 2014</p>
	</div>
</div>

app/views/master_layouts/_messages.html.erb
<% unless flash.notice.nil? %>
    <div class="alert alert-<%= flash[:type].nil? ? "success" : flash[:type] %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, flash.notice %>
    </div>
<% end %>

app/views/master_layouts/_navbar.html.erb
<% admin_controller = ["admin","users","units","streams","user_sessions"] %>
<div class="navbar navbar-default navbar-static-top navbar-collapse">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Enrolment Planner", planner_index_path, class: "navbar-brand" %>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<% if params[:controller] == "planner" %>
				<li class="active"><%= link_to 'Planner', planner_index_path %></li>
				<li><%= link_to 'Admin Portal', admin_index_path %></li>
			<% elsif admin_controller.include? params[:controller] %>
				<li><%= link_to 'Planner', planner_index_path %></li>
				<li class="active"><%= link_to 'Admin Portal', admin_index_path %></li>
			<% else %>
				<li><%= link_to 'Planner', planner_index_path %></li>
				<li><%= link_to 'Admin Portal', admin_index_path %></li>
			<% end %>
			<% if current_user %>
				<li class="small"><%= link_to "Register", new_user_path %></li>
				<li class="small"><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
				<li class="small"><%= link_to "Logout", logout_path %></li>
			<% end %>
		</ul>
	</div>
</div>

app/views/master_layouts/_sembox.html.erb
<%
year = (semester+1)/2
sem = (semester+1)%2+1
numUnits = session[:semesters][count].length
%>

<% if (session[:semesters][count][0].to_i >= 0) %>
<div class="col-md-6<%=push!=0 ? " col-md-offset-6" : "" %>">
	<div class="thumbnail">
		<div style="text-align: center; font-size: 14px;">Year <%=year%> Semester <%=sem%></div>

		<div class="caption">
			<table class="table table-condensed table-hover unitsList semtable" semtable-id="<%=semester-1%>" sem="<%=sem%>">
			<tbody>
				<% session[:semesters][count.to_i].each_with_index do |uid, i| %>
					<% unit = Unit.where(:id => uid).first %>
					<% if (session[:semesters][count][i].to_i > 0) %>
						<tr class="unitRow" credit-points="<%=unit.creditPoints%>" sem-avail="<%=unit.semAvailable==0 ? "Both" : unit.semAvailable %>" uid="<%=unit.id%>" >
							<td style="font-size:11px; text-align:center;"><%= unit.unitCode %></td>
							<td style="font-size:11px;"><%= unit.unitName %></td>
							<td style="font-size:11px; text-align:center;"><%= unit.semAvailable==0 ? "Both" : unit.semAvailable %></td>
						</tr>
					<% end %>
				<% end %>
			</tbody>
			<tfoot>
				<tr class="creditsRow">
					<td colspan="2"><div style="font-size:11px; text-align:right;">Credit points: 
					<% if (session[:semesters][count][0] != 0) %>
						<%= calc_sem_credits(count.to_i) %>
					<% else %>
						0
					<% end %>
					</div>
					</td>
				</tr>
			</tfoot>
			</table>
		</div>
	</div>
</div>
<% end %>